# Generated by Django 3.1.6 on 2021-02-19 12:15

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.filter', verbose_name='Kateqoriya adı')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(choices=[('Tikinti-materiallari', 'Tikinti-materiallari'), ('Pencere-ve-qapi', 'Pencere-ve-qapi'), ('Isitme-ve-soyutma', 'Isitme-ve-soyutma'), ('Santexnika', 'Santexnika'), ('Doseme-tavan-ve-dam', 'Doseme-tavan-ve-dam'), ('Temir-ve-tikinti-aletleri', 'Temir-ve-tikinti-aletleri')], max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=220, verbose_name='Product Kudu')),
                ('title', models.CharField(max_length=220)),
                ('price', models.CharField(max_length=220)),
                ('image', models.ImageField(blank=True, upload_to='static/images/product/')),
                ('category', mptt.fields.TreeManyToManyField(blank=True, null=True, to='product.Filter')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory')),
            ],
        ),
    ]
