# Generated by Django 3.1.6 on 2021-02-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/home/')),
            ],
        ),
    ]
