# Generated by Django 3.1.6 on 2021-02-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='text',
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
