# Generated by Django 3.1.6 on 2021-02-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210216_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, default=0, upload_to='static/images/home/'),
            preserve_default=False,
        ),
    ]
