# Generated by Django 3.1.6 on 2021-02-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('telefon', 'TELEFON'), ('meiset texnikasi', 'MEISET TEXNIKASI')], default=0, max_length=200),
            preserve_default=False,
        ),
    ]
