# Generated by Django 3.1.6 on 2021-02-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0003_auto_20210215_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='category',
            new_name='list_category',
        ),
    ]
