# Generated by Django 3.1.6 on 2021-02-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_auto_20210215_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=220)),
                ('number', models.CharField(max_length=220)),
            ],
        ),
        migrations.DeleteModel(
            name='Links',
        ),
    ]
