# Generated by Django 3.1.6 on 2021-02-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_auto_20210217_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='facebook',
            field=models.CharField(default=0, max_length=220),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram',
            field=models.CharField(default=0, max_length=220),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(default=0, max_length=220),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='youtube',
            field=models.CharField(default=0, max_length=220),
            preserve_default=False,
        ),
    ]
