# Generated by Django 3.1.6 on 2021-02-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0006_auto_20210218_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='facebook',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='youtube',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
