# Generated by Django 3.1.6 on 2021-02-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0007_auto_20210218_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=220)),
            ],
        ),
    ]
