# Generated by Django 3.1.6 on 2021-02-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0008_create_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Create_Post',
            new_name='Email',
        ),
    ]
